### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by imirfanul** [anasmorahhib/3D-CNN-Gesture-recognition#10]
Brother , I don't have well configured Laptop so  I used [](**https://www.kaggle.com/toxicmender/20bn-jester** ) this dataset  and I have to use only 4 kind of class from data set to control powerpoint. So how can I only get those 4 kind class from whole dataset ? 
Actually I want to make a sort dataset from this .

**Comment by anasmorahhib** [comment]
Hello,
you can use this script
https://github.com/anasmorahhib/3D-CNN-Gesture-recognition/blob/master/training-sample.py
change "class_"  list with 4 kind of class you want.

**Comment by imirfanul** [comment]
Thank you so much brother ❤❤
